# Generated by Django 4.0 on 2022-03-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('regid', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('companyowner', models.CharField(max_length=100)),
                ('websiteid', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.login')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatename', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.login')),
            ],
        ),
    ]
