# Generated by Django 4.0.2 on 2022-03-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatename', models.CharField(max_length=100)),
                ('candidatemail', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('keyskill', models.CharField(max_length=800)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resume')),
                ('applystatus', models.IntegerField(default=0)),
                ('candlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.login')),
                ('vacancyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.vacancies')),
            ],
        ),
    ]
