# Generated by Django 4.0 on 2022-03-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=800)),
                ('keyskill', models.CharField(max_length=800)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('no_opening', models.IntegerField()),
                ('publishedon', models.CharField(max_length=50)),
                ('lastdate', models.CharField(max_length=50)),
                ('joblocation', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.company')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.login')),
            ],
        ),
    ]
